# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd261af589705e0733333050e9376ecc7082bf96430d3b6614b77c0819d0fe5b3a54f7e26c5b02804eaada6c06b3b4cdd37df3dede85c88414cce87a6bf07752

test:
  secret_key_base: c1b4bbc7fa2bf493604dc555bc2404569bd43d78d4564f687745fec765fb280bf0e7575514834862f9dff48542ac956e0bbcd2cb90ed195c0e456f5ff05f0d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
